### ISSUE TITLE
RunWith support runs test suites

### ISSUE THREAD

**Issue by szeiger** [sbt/junit-interface#14]
The suite runner should be exempt from RunWith support to prevent tests in suites from running multiple times.

**Comment by schallerala** [comment]
For others getting here from Google and struggling to find a way to run a _suite_ of test classes in a specific order, without the `Suite` runner which is ignored by this JUnit interface, I inspired myself with the `Enclosed` runner and allowed to run inner classes in a specific order with a custom runner like [my gist: OrderableEnclosed](https://gist.github.com/schallerala/bacfeeb2b57d6ed7bc95e96f83ee0331)
