### ISSUE TITLE
Document running individual test methods

### ISSUE THREAD

**Issue by jroper** [sbt/junit-interface#36]
The specs2 SBT test runner allows running individual specs:

https://github.com/sbt/sbt/issues/911

junit-interface could likewise provide support for running individual test methods.

**Comment by johanatan** [comment]
I'm getting `Argument unrecognized by ScalaTest's Runner: *pattern` when invoking like:
```
sbt test-only -- *pattern
```

**Comment by johanatan** [comment]
Also, passing a single `-q` seems to effectively suppress a lot of output but when I do:

`-q *pattern` I get this error:
```
Discovery suffixes (-q) is not supported when running ScalaTest from sbt; Please use sbt's test-only or test filter instead
```

**Comment by johanatan** [comment]
Seems like scalatest is involved here somehow although my build.sbt doesn't mention it and only imports this junit-interface for testing.

**Comment by eed3si9n** [comment]
https://github.com/sbt/junit-interface/pull/107
