### ISSUE TITLE
-a option should be the default

### ISSUE THREAD

**Issue by benmccann** [sbt/junit-interface#62]
The error messages are quite unhelpful if `-a` is not set. This has caused me countless hours of frustration before I realized the option existed. 

When you have output like the following, it's impossible to figure out what line the test is failing on when it's a large file with multiple assertions. All we get is "failed: null" and no line number or stacktrace, which was a recurring source of annoyance for the developers on our team.

    $ ./activator test
    [info] Loading project definition from /home/bmccann/src/play-java/project
    [info] Set current project to play-java (in build file:/home/bmccann/src/play-java/)
    [error] Test ApplicationTest.simpleCheck failed: null, took 0.02 sec
    [error] Failed: Total 3, Failed 1, Errors 0, Passed 2
    [error] Failed tests:
    [error] 	ApplicationTest
    [error] (test:test) sbt.TestsFailedException: Tests unsuccessful
    [error] Total time: 5 s, completed Nov 20, 2014 10:16:48 PM

**Comment by DavidPerezIngeniero** [comment]
I fully agree, otherwise you know a class fails, but not which method or why.

**Comment by anildes** [comment]
Where shoulld we put this config in build.sbt ?

**Comment by DavidPerezIngeniero** [comment]
Yes `build.sbt`.

**Comment by anildes** [comment]
Thanks Dave

**Comment by benmccann** [comment]
I pushed a fix here: https://github.com/sbt/junit-interface/commit/ae2611c0797a70602df542db0684ad88aa5a4665
