### ISSUE TITLE
Reporting tests as skipped instead of ignored

### ISSUE THREAD

**Issue by benmccann** [sbt/junit-interface#63]
Shouldn't this be `Status.Ignored` instead of `Status.Skipped` in `EventDispatcher.java`? I'm not really sure when you'd report a test as skipped, but I'd imagine if you mark a test with @Ignore then it should be reported as ignored instead of skipped given that a [Status](https://github.com/sbt/test-interface/blob/master/src/main/java/sbt/testing/Status.java) exists for both of those

```
@Override
public void testIgnored(Description desc)
{
  postIfFirst(new InfoEvent(desc, Status.Skipped) {
    void logTo(RichLogger logger) {
      logger.info("Test "+ansiName+" ignored");
    }
  });
}
```

**Comment by eed3si9n** [comment]
This was fixed in https://github.com/sbt/junit-interface/pull/97
