### ISSUE TITLE
--include/exclude-categories ignored

### ISSUE THREAD

**Issue by ejain** [sbt/junit-interface#64]
As far as I can tell, neither `--include-categories=` nor `--include-categories=` do anything. Given e.g. 

    @org.junit.experimental.categories.Category(com.example.FastTests.class)
    public class ExampleTest {
      @org.junit.Test
      public void test() {
        ...
      }
    }

...both `test-only -- -v --include-categories=com.example.FastTests` and `test-only -- -v --exclude-categories=com.example.FastTests` run all tests.

**Comment by squito** [comment]
I think this might be fixed in 0.11.  I just experienced it in 0.10, but it went away after upgrading to 0.11

**Comment by ejain** [comment]
I'm using sbt 0.13.5, so perhaps this broke again, or else there could be an issue when running tests via the Typesafe activator.

**Comment by squito** [comment]
sorry I should have been more clear -- I'm taking about version 0.11 of _junit-interface_.  I am using sbt 0.13.6.  I am not using typesafe activator, so maybe thats the issue?

**Comment by ejain** [comment]
Looks like that's it: With sbt 0.13.6 and junit-interface 0.11 (instead of 0.11-RC1), `--include-categories` works as expected.
