### ISSUE TITLE
support opening and closing quotes in --tests

### ISSUE THREAD

**Issue by fommil** [sbt/junit-interface#72]
Counter-inutitively, `--tests="foo"` does not work as expected, it must be `--tests=foo` (no `"`).

This always catches me out.

**Comment by szeiger** [comment]
All argument parsing is done by sbt and the test framework gets an array of Strings, similar to how a command line application gets its arguments from the shell. If you want to quote, it has to be around the entire argument, but with `--tests` there should never be a reason to do that.

**Comment by fommil** [comment]
it's more that one is used to passing regexes around inside `"..."` so it's easy to forget that it's not needed.
