### ISSUE TITLE
Junit 5 Compatibility

### ISSUE THREAD

**Issue by ShahBinoy** [sbt/junit-interface#75]
Is there a road map to add JUnit 5 Compatibility.

**Comment by domdorn** [comment]
this is already working for me.. I just needed to add these to my dependencies:

```
    "org.junit.platform" % "junit-platform-runner" % "1.0.0-M3" % "test",
    "org.junit.jupiter" % "junit-jupiter-engine" % "5.0.0-M3" % "test",
    "org.junit.vintage" % "junit-vintage-engine" % "4.12.0-M3" % "test",

    // This provides the SBT-TestInterface for JUnit.
    // Without this on the classpath, no tests will be executed by SBT
    "com.novocode" % "junit-interface" % "0.11" % "test"

```

You'll have to annotate your test classes with 
`@RunWith(JUnitPlatform.class)
`

**Comment by DmytroMitin** [comment]
> this is already working for me.. I just needed to add these to my dependencies: ...

Currently it isn't.
```
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions
import org.junit.platform.runner.JUnitPlatform
import org.junit.runner.RunWith

@RunWith(classOf[JUnitPlatform])
class MyTest {
  @org.junit.jupiter.api.Test
  def testEquals5(): Unit = {
    Assertions.assertEquals(5, 2 + 2, () => "")
  }
}
```
```
scalaVersion := "2.12.3"
libraryDependencies += "org.junit.jupiter" % "junit-jupiter-api" % "5.0.0-RC3" % Test
libraryDependencies += "org.junit.vintage" % "junit-vintage-engine" % "4.12.0-RC3" % Test
libraryDependencies += "org.junit.platform" % "junit-platform-runner" % "1.0.0-RC3" % Test
libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % Test
```
`sbt.version = 0.13.16`
```
$ sbt test
[info] Loading global plugins from /home/dmitin/.sbt/0.13/plugins
[info] Loading project definition from /home/dmitin/Projects/testing/junitscalademo/project
[info] Set current project to junitscalademo (in build file:/home/dmitin/Projects/testing/junitscalademo/)
[info] Compiling 1 Scala source to /home/dmitin/Projects/testing/junitscalademo/target/scala-2.12/test-classes...
авг 25, 2017 7:31:11 PM org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using JUnitPlatform runner: MyTest
авг 25, 2017 7:31:11 PM org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using JUnitPlatform runner: MyTest
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 5 s, completed 25.08.2017 19:31:11
```
instead of failing.

**Comment by eed3si9n** [comment]
Now that JUnit 5 is out, I think it makes sense to support this from junit-interface.
Contribution would be greatly appreciated.

**Comment by sbahmani** [comment]
I test `sbt test` in console and nothing(just some info log), but with Idea all test run!

**Comment by JFCote** [comment]
Same problem here. I followed @domdorn post to the letter but sbt test doesn't find any test. Running with IntelliJ IDEA work perfectly. Also, I think it is very strange that we need to include JUnit 4 in the classpath to run pure Junit 5 tests.

**Comment by smarter** [comment]
https://github.com/maichler/sbt-jupiter-interface is an implementation of sbt test interface for JUnit 5. Maybe it could be merged with or replace the official junit-interface? /cc @maichler

**Comment by eximius313** [comment]
Are there any plans to finally support Junit5 in sbt?

**Comment by hepin1989** [comment]
@eed3si9n any update on this?

**Comment by SethTisue** [comment]
sounds like people should be using, and/or contributing to, https://github.com/maichler/sbt-jupiter-interface

**Comment by daggerok** [comment]
Cannot run junit 5 tests (even *Test.java) when testing scala code

**Comment by mkurz** [comment]
@eed3si9n so the solution for this issue is using https://github.com/maichler/sbt-jupiter-interface? Maybe this should be mentioned in the readme? WDYT?

**Comment by eed3si9n** [comment]
Done in https://github.com/sbt/junit-interface/pull/107

**Comment by domdorn** [comment]
@eed3si9n if @maichler would be ok with that, would it be ok with you to move his repo to github.com/sbt/junit5-interface ? that way, it would be more straightforward for (especially new) users. 
What do you think? if its ok for you, I would reach out to him.

**Comment by eed3si9n** [comment]
https://www.scala-sbt.org/1.x/docs/Community-Plugins.html
sbt organization is available for all plugins.
