### ISSUE TITLE
Does not report failures in cucumber scenario outline results

### ISSUE THREAD

**Issue by alexmsmartins** [sbt/junit-interface#84]
Cucumber tests with Data Tables will pass with failing examples as long as the first example passes.

This happens because all the examples have the same fully qualified name that comes from the scenario outline description.

I have submitted a PR to fix this #83 .

**Comment by alexmsmartins** [comment]
I am sorry but, is this project dead?

**Comment by gaeljw** [comment]
Same happens if two Cucumber scenarios have the same name.

See https://github.com/cucumber/cucumber-jvm-scala/issues/22

**Comment by lefou** [comment]
Related: #95

**Comment by gaeljw** [comment]
For anyone coming here, this issue is now "solved" by Cucumber since few versions as they implemented a unique name for each scenario with a suffix.

The underlying issue can still appear but not in Cucumber context.
