### ISSUE TITLE
Publish a new release of junit-interface?

### ISSUE THREAD

**Issue by smarter** [sbt/junit-interface#94]
junit-interface 0.11 was released over 6 years ago. Since then, various improvements have been pushed to this repo including https://github.com/sbt/junit-interface/commit/20183572cb15cc302199b48824bd1812a5d4941e last year which provides some nice improvements to the test output. Would it be possible to publish a new release to maven?

**Comment by smarter** [comment]
@szeiger it looks like novocode.com is your domain so presumably you're the one who would make a release here since junit-interface is published under com.novocode?

**Comment by smarter** [comment]
Friendly ping :slightly_smiling_face:

**Comment by unkarjedy** [comment]
Another friendly ping :) 

Would be also great if these were included into 0.12 as well:  #98, #97

@szeiger @benmccann

**Comment by benmccann** [comment]
I have not used sbt in many years. I'm not the right person to ask about this

**Comment by SethTisue** [comment]
is there is a strong need to stay on com.novocode, or could we just move this to be published under a different org? perhaps that would be the path of least resistance here.

(I can't afford to get _too_ involved in this repo, as I've already got too many other things going, but I do have merge rights, so I can assist to some extent with getting things moving again)

**Comment by SethTisue** [comment]
@unkarjedy might you be interested in taking over the publishing...?

**Comment by unkarjedy** [comment]
@SethTisue 
I could do that for some time.

**Comment by SethTisue** [comment]
@eed3si9n is this repo a candidate for being published under some existing sonatype account you manage, or would @unkarjedy need to publish under his own org?

i know that you aren’t providing publishing to just anybody anymore, but I’m genuinely unsure whether you might still be open to hooking up certain core, widely used repos like this one

**Comment by eed3si9n** [comment]
> @eed3si9n is this repo a candidate for being published under some existing sonatype account you manage

Yea. This sounds like a good candidate to pick up.

**Comment by eed3si9n** [comment]
I've invited @ashawley and @unkarjedy to https://github.com/orgs/sbt/teams/junit-interface team.
I can set up tag based publishing so they'll both have rights to cut a release whenever.

**Comment by eed3si9n** [comment]
I just released junit-interface 0.12, 0.13, 0.13.1, and 0.13.2 corresponding to JUnit 4.12, 4.13, 4.13.1, and 4.13.2.
